services:
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: greenlight
    ports:
    - "5432:5432"
    volumes:
    - greenlight_db_data:/var/lib/postgresql/data

  valkey:
    image: valkey/valkey:latest
    ports:
      - "6379:6379"

  db_test:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: greenlight
    ports:
    - "5433:5432"
    volumes:
    - greenlight_db_test:/var/lib/postgresql/data

volumes:
  greenlight_db_data:
  greenlight_db_test:
